(()=>{
const BUILD='20260927-1';
const trips=Array.isArray(window.TRAVEL_COMMAND_CENTER_TRIPS)&&window.TRAVEL_COMMAND_CENTER_TRIPS.length?window.TRAVEL_COMMAND_CENTER_TRIPS:[window.TRAVEL_COMMAND_CENTER_ACTIVE_TRIP].filter(Boolean);
const requestedTrip=new URLSearchParams(location.search).get('trip');
const active=trips.find(trip=>trip.id===requestedTrip)||trips.slice().sort((a,b)=>a.start.localeCompare(b.start))[0];
const archives=Array.isArray(window.TRAVEL_COMMAND_CENTER_ARCHIVES)?window.TRAVEL_COMMAND_CENTER_ARCHIVES:[];
const app=document.getElementById('app');
const e=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const fmt=date=>{try{return new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric'}).format(new Date(`${date}T12:00:00`))}catch{return date}};

function archiveCards(){
  if(!archives.length)return'<section class="panel empty-card"><h3>No archived trips yet</h3><p>Completed trips will appear here automatically.</p></section>';
  return`<div class="archive-grid">${archives.map(trip=>`<a class="archive-card" href="${e(trip.url)}" style="background-image:url('${e(trip.coverImage)}')"><div class="archive-copy"><span class="archive-state">ARCHIVED · COMPLETE</span><span class="archive-arrow">›</span><h3>${e(trip.title)}</h3><p>${e(trip.dates)}</p><div class="archive-route">${(trip.stops||[]).map(stop=>`<span>${e(stop)}</span>`).join('')}</div></div></a>`).join('')}</div>`;
}

function archiveSection(){
  const count=archives.length;
  return`<details class="archive-disclosure" id="archives"><summary><span class="archive-summary-icon" aria-hidden="true">🗃️</span><span class="archive-summary-copy"><strong>Past trips</strong><small>${count} ${count===1?'journey':'journeys'} in your archive</small></span><span class="archive-summary-action">Browse archive <span aria-hidden="true">⌄</span></span></summary><div class="archive-disclosure-content" data-archive-list></div></details>`;
}

function travelPartySection(trip){
  const party=trip.publicTravelParty;
  if(!party)return'';
  const companions=party.companions||[];
  return`<section class="party-section" aria-labelledby="party-heading"><div class="section-title" id="party-heading">Travel party <span>People and reservations</span></div><div class="panel party-panel"><div class="party-main"><span class="party-symbol" aria-hidden="true">👥</span><div><span class="kicker">YOUR CRUISE RESERVATION</span><strong>${e(party.reservation)}</strong><p class="party-names">${(party.names||[]).map(e).join(' · ')}</p></div></div>${companions.length?`<div class="party-linked">${companions.map(group=>`<div class="party-linked-row"><span class="party-linked-dot" aria-hidden="true"></span><div><strong>${e(group.names)}</strong>${group.reservation?`<span class="party-reservation">Linked reservation ${e(group.reservation)}</span>`:''}${group.note?`<p>${e(group.note)}</p>`:''}</div></div>`).join('')}</div>`:''}</div></section>`;
}

function shell(hero,content,dock=true){
  const archiveMarkup=`<div class="section-title" id="archives">Archived trips</div>${archiveCards()}`;
  const displayContent=content.replace(archiveMarkup,archiveSection());
  app.innerHTML=`<div class="site-header"><a class="site-brand" href="#top" aria-label="Travel Command Center home"><span class="brand-mark">✦</span><span><strong>Travel Command Center</strong><small>Every journey, in one place</small></span></a><a class="header-link" href="${trips.length>1?'#trips':'#archives'}">${trips.length>1?'All trips':'Past trips'} <span aria-hidden="true">↗</span></a></div>${hero}<main class="main">${displayContent}<div class="footer">Travel Command Center · upcoming trips organized · every journey preserved</div></main>${dock?`<nav class="tool-dock" aria-label="Quick tools"><div class="dock-inner"><a href="#top"><span>🏠</span>Home</a><a href="#archives"><span>🗃️</span>Past Trips</a><button type="button" data-tool="translate"><span>🌐</span>Translate</button><button class="accent-tool" type="button" data-tool="hungry"><span>🍜</span>Hungry?</button></div></nav>`:''}`;
  wireCommon();
}

function renderEmpty(){
  const hero=`<header class="hero" id="top" style="background-image:url('https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&q=88&w=1600')"><button class="button refresh-button" id="refreshDashboard" type="button"><span class="refresh-icon">↻</span> Refresh</button><span class="brand-chip">Mike's Travel Command Center</span><h1>Ready for the<br>next adventure.</h1><p class="hero-copy">One beautifully organized trip at a time—with every completed journey safely archived.</p><div class="hero-actions"><a class="button primary" href="#next-trip">Build my next trip ↓</a><a class="button" href="#archives">View past trips</a></div></header>`;
  const content=`<section class="panel status-panel"><div class="kicker">NO ACTIVE TRIP</div><h2>Your dashboard is ready.</h2><p>Send Dex your trip spreadsheet when the next destination takes shape. The active dashboard will be generated from the verified, share-safe details.</p><div class="offline-row" id="offlineStatus"><span class="offline-dot"></span><span>Preparing offline access…</span></div></section><div class="section-title" id="next-trip">How the next trip gets loaded</div><section class="panel empty-card"><h3>Spreadsheet in. Command center out.</h3><p>Notes, transportation, hotels, activities and booking details can all be included in your source spreadsheet. Private booking identifiers stay out of the public build.</p><div class="workflow"><div class="workflow-step"><span class="step-number">1</span><div><b>Send the spreadsheet to Dex</b><small>Any reasonable layout is fine; PDFs and notes can accompany it.</small></div></div><div class="workflow-step"><span class="step-number">2</span><div><b>Details are normalized and checked</b><small>Dates, cities, hotels and transportation are validated; private fields are separated.</small></div></div><div class="workflow-step"><span class="step-number">3</span><div><b>The next trip becomes active</b><small>The same mobile, weather, nearby and offline tools adapt to the destination.</small></div></div></div></section>${archiveSection()}`;
  shell(hero,content);
}

function validateTrip(trip){
  const errors=[];
  if(!trip||typeof trip!=='object')errors.push('Trip data is missing');
  if(!trip?.id)errors.push('Trip id is required');
  if(!trip?.title)errors.push('Trip title is required');
  if(!trip?.start||!trip?.end)errors.push('Trip start and end dates are required');
  if(!Array.isArray(trip?.cities)||!trip.cities.length)errors.push('At least one city is required');
  return errors;
}

function dayCard(day){return`<div class="item-card"><span class="kicker">${e(day.date||day.label)}</span><b>${e(day.title)}</b>${day.summary?`<p>${e(day.summary)}</p>`:''}${day.items?.length?`<div class="chips">${day.items.map(x=>`<span class="chip">${e(x)}</span>`).join('')}</div>`:''}</div>`}
function phaseCards(phases){return`<div class="phase-grid">${phases.map(phase=>`<a class="phase-card phase-${e(phase.id)}" href="#${e(phase.id)}"><span class="phase-icon">${e(phase.icon||'✦')}</span><div><small>${e(phase.label||'TRIP PART')} · ${e(phase.dates||'')}</small><b>${e(phase.title)}</b><p>${e(phase.summary||'')}</p><em>${e(phase.status||'')}</em></div><span class="phase-arrow">›</span></a>`).join('')}</div>`}
function readinessCards(items){return`<div class="readiness-grid">${items.map(group=>`<section class="panel readiness-card ${e(group.tone||'')}"><div class="readiness-head"><span>${e(group.icon||'•')}</span><h3>${e(group.title)}</h3></div><ul>${(group.items||[]).map(item=>`<li>${e(item)}</li>`).join('')}</ul></section>`).join('')}</div>`}
function tripCards(){if(trips.length<2)return'';return`<div class="section-title" id="trips">Upcoming trips <span>${trips.length} journeys</span></div><div class="trip-grid">${trips.slice().sort((a,b)=>a.start.localeCompare(b.start)).map(trip=>`<a class="trip-card ${trip.id===active.id?'active-trip-card':''}" href="?trip=${encodeURIComponent(trip.id)}" ${trip.id===active.id?'aria-current="page"':''}><span class="trip-card-photo" style="background-image:url('${e(trip.heroImage)}')"></span><span class="trip-card-body"><span class="trip-card-date">${e(trip.eyebrow||`${fmt(trip.start)} – ${fmt(trip.end)}`)}</span><strong>${e(trip.title)}</strong><span class="trip-card-location">${e(trip.location||trip.subtitle||'')}</span><span class="trip-card-action">${trip.id===active.id?'Viewing itinerary':'View itinerary'} <span aria-hidden="true">↗</span></span></span></a>`).join('')}</div>`}
function cityCard(city){return`<details class="panel city-card" id="${e(city.id)}"><summary style="background-image:url('${e(city.image)}')"><span class="city-symbol">${e(city.icon||'📍')}</span><span class="city-heading"><b>${e(city.name)}</b><small>${e(city.dates||'')}</small></span><span>⌄</span></summary><div class="city-body">${city.summary?`<h4>The vibe</h4><p>${e(city.summary)}</p>`:''}${city.days?.length?`<h4>Day plans</h4>${city.days.map(dayCard).join('')}`:''}${city.hotel?`<h4>Hotel</h4><div class="item-card"><b>${e(city.hotel.name)}</b><p>${e(city.hotel.address||'')}</p><div class="chips">${(city.hotel.amenities||[]).map(x=>`<span class="chip">${e(Array.isArray(x)?x.join(' '):x)}</span>`).join('')}</div>${city.hotel.mapQuery?`<a class="button" target="_blank" rel="noopener" href="https://maps.apple.com/?q=${encodeURIComponent(city.hotel.mapQuery)}">📍 Map</a>`:''}</div>`:''}${city.highlights?.length?`<h4>Highlights</h4>${city.highlights.map(x=>`<div class="item-card"><b>${e(x.name||x)}</b>${x.note?`<p>${e(x.note)}</p>`:''}</div>`).join('')}`:''}${city.nightlife?.length?`<h4>After dark</h4>${city.nightlife.map(x=>`<div class="item-card"><b>${e(x.name||x)}</b>${x.note?`<p>${e(x.note)}</p>`:''}</div>`).join('')}`:''}${city.photoSpots?.length?`<h4>Photo spots</h4>${city.photoSpots.map(x=>`<div class="item-card"><b>${e(x.name||x)}</b>${x.note?`<p>${e(x.note)}</p>`:''}</div>`).join('')}`:''}<div class="hero-actions"><button class="button" type="button" data-weather="${e(city.name)}" data-weather-lat="${e(city.coordinates?.lat||'')}" data-weather-lng="${e(city.coordinates?.lng||'')}">☀️ 7-day weather</button><button class="button" type="button" data-tool="spas">♨️ Nearby spas</button></div></div></details>`}

function renderActive(trip){
  const errors=validateTrip(trip);if(errors.length){renderError(errors);return}
  const cities=trip.cities||[];
  const today=new Date().toISOString().slice(0,10),todayPlan=(trip.days||[]).find(x=>x.date===today);
  const before=today<trip.start,after=today>trip.end;
  const status=before?{k:'TRIP COUNTDOWN',h:`${Math.max(0,Math.ceil((new Date(`${trip.start}T12:00:00`)-new Date())/86400000))} days to go`,p:'Your next command center is ready.'}:after?{k:'TRIP COMPLETE',h:'What a trip.',p:'This trip is ready to be moved into the archive.'}:todayPlan?{k:'LIVE TRIP · TODAY',h:todayPlan.title,p:todayPlan.summary}:{k:'LIVE TRIP',h:'Today is yours.',p:'Open the city details for today’s plan.'};
  const hero=`<header class="hero" id="top" style="background-image:url('${e(trip.heroImage)}')"><button class="button refresh-button" id="refreshDashboard" type="button"><span class="refresh-icon">↻</span> Refresh</button><span class="brand-chip">${e(trip.eyebrow||`${trip.title} · ${fmt(trip.start)} – ${fmt(trip.end)}`)}</span><h1>${e(trip.headline||trip.title)}</h1><p class="hero-copy">${e(trip.subtitle||'Everything for the journey, in one pocket guide.')}</p><nav class="route-scroll">${cities.map(c=>`<a href="#${e(c.id)}">${e(c.name)}</a>`).join('')}</nav></header>`;
  const quick=`<div class="quick-grid"><a class="quick-card" href="#chapters"><span>🧳</span><b>Trip chapters</b><small>${e(trip.quickPartsLabel||'Explore this itinerary')}</small></a><a class="quick-card" href="#travel"><span>✈️</span><b>Travel</b><small>Transport and stays</small></a><a class="quick-card" href="#timeline"><span>🧭</span><b>Timeline</b><small>Everything in order</small></a><a class="quick-card" href="#archives"><span>🗃️</span><b>Past Trips</b><small>Completed journeys</small></a></div>`;
  const transport=(trip.transport||[]).map(item=>`<article class="panel timeline-item"><span class="timeline-icon">${e(item.icon||({flight:'✈️',train:'🚄',hotel:'🏨',transfer:'🚘'}[item.type]||'📍'))}</span><div><time>${e(item.date||'')}</time><b>${e(item.title)}</b><p>${e(item.details||'')}</p>${item.notes?.length?`<div class="chips">${item.notes.map(x=>`<span class="chip">${e(x)}</span>`).join('')}</div>`:''}</div></article>`).join('');
  const timeline=(trip.timeline||trip.transport||[]).map(item=>`<article class="panel timeline-item"><span class="timeline-icon">${e(item.icon||'•')}</span><div><time>${e(item.date||item.time||'')}</time><b>${e(item.title)}</b><p>${e(item.details||item.summary||'')}</p></div></article>`).join('');
  const support=(trip.support||[]).map(x=>`<article class="panel support-card"><h3>${e(x.title)}</h3>${x.details?`<p>${e(x.details)}</p>`:''}${x.phone?`<a class="button" href="tel:${e(x.phone)}">📞 Call</a>`:''}${x.url?`<a class="button" target="_blank" rel="noopener" href="${e(x.url)}">Open ↗</a>`:''}</article>`).join('');
  const content=`<section class="panel status-panel"><div class="kicker">${status.k}</div><h2>${e(status.h)}</h2><p>${e(status.p)}</p><div class="offline-row" id="offlineStatus"><span class="offline-dot"></span><span>Preparing offline access…</span></div></section>${tripCards()}${trip.phases?.length?`<div class="section-title">${trip.phasesTitle||'Trip parts'}</div>${phaseCards(trip.phases)}`:''}${trip.readiness?.length?`<div class="section-title">Booking snapshot</div>${readinessCards(trip.readiness)}`:''}<div class="section-title">Quick access</div>${quick}<div class="section-title" id="chapters">Trip chapters · tap to explore</div>${cities.map(cityCard).join('')}<div class="section-title" id="travel">Transportation and stays</div><section class="travel-grid">${transport||'<div class="panel empty-card"><p>Transportation details will appear here.</p></div>'}</section><div class="section-title" id="timeline">Overall timeline</div><section class="travel-grid">${timeline||'<div class="panel empty-card"><p>The complete timeline will appear here.</p></div>'}</section>${support?`<div class="section-title">Trip support</div><section class="travel-grid">${support}</section>`:''}${trip.sharedPhotosUrl?`<div class="section-title">Shared photos</div><a class="panel empty-card" style="display:block;color:white;text-decoration:none" target="_blank" rel="noopener" href="${e(trip.sharedPhotosUrl)}"><h3>📸 Open shared trip photos</h3><p>Upload and enjoy everyone’s pictures from the journey.</p></a>`:''}<div class="section-title" id="archives">Archived trips</div>${archiveCards()}`;
  const tripList=tripCards();
  shell(hero,content.replace(tripList,`${tripList}${travelPartySection(trip)}`));
}

function renderError(errors){shell(`<header class="hero" id="top"><span class="brand-chip">Travel Command Center</span><h1>Trip data needs attention.</h1><p class="hero-copy">The active trip was not published because required information is missing.</p></header>`,`<section class="panel empty-card"><h3>Validation stopped this release</h3>${errors.map(x=>`<p>• ${e(x)}</p>`).join('')}</section><div class="section-title" id="archives">Archived trips</div>${archiveCards()}`,false)}

function modal(title,body){document.getElementById('toolModal')?.remove();const el=document.createElement('div');el.id='toolModal';el.className='modal';el.innerHTML=`<section class="sheet" role="dialog" aria-modal="true"><div class="sheet-head"><h2>${e(title)}</h2><button class="close" type="button" aria-label="Close">×</button></div><div id="toolBody">${body}</div></section>`;document.body.appendChild(el);requestAnimationFrame(()=>el.classList.add('show'));const close=()=>{el.classList.remove('show');setTimeout(()=>el.remove(),180)};el.querySelector('.close').addEventListener('click',close);el.addEventListener('click',event=>{if(event.target===el)close()});return el}

function nearby(kind){const isFood=kind==='hungry',title=isFood?'Hungry? 🍜':'Nearby Spas ♨️',endpoint=isFood?'/api/restaurants':'/api/spas';const el=modal(title,`<p class="tool-note">Using your phone’s location to find highly rated options close to where you are standing.</p><div class="result-list" id="nearbyResults"><div class="result-card">Finding your precise location…</div></div>`),results=el.querySelector('#nearbyResults');if(!navigator.geolocation){results.innerHTML='<div class="result-card">Location is not available on this device.</div>';return}navigator.geolocation.getCurrentPosition(async position=>{try{const {latitude,longitude}=position.coords;const response=await fetch(`${endpoint}?lat=${encodeURIComponent(latitude)}&lng=${encodeURIComponent(longitude)}`);if(!response.ok)throw new Error();const data=await response.json(),items=data[isFood?'restaurants':'spas']||[];results.innerHTML=items.length?items.map(x=>`<article class="result-card"><b>${e(x.name)}</b><p class="tool-note">${x.rating?`★ ${e(x.rating)} · `:''}${e(x.address||x.type||'')}</p>${x.maps?`<a target="_blank" rel="noopener" href="${e(x.maps)}">Open in Maps ↗</a>`:''}</article>`).join(''):'<div class="result-card">No nearby results were returned.</div>'}catch{results.innerHTML='<div class="result-card">Live results are unavailable. Check your connection and try again.</div>'}},()=>{results.innerHTML='<div class="result-card">Allow Location access in your iPhone settings, then try again.</div>'},{enableHighAccuracy:true,timeout:12000,maximumAge:30000})}

function translate(){const language=active?.destinationLanguage||'the local language';modal('Translate 🌐',`<p class="tool-note">Choose the translator that works best on your phone. Download ${e(language)} before departure for offline use.</p><div class="result-list"><a class="result-card" href="https://apps.apple.com/app/translate/id1514844618" target="_blank" rel="noopener"><b>🍎 Apple Translate</b><p class="tool-note">Best fit for iPhone and downloadable offline languages.</p></a><a class="result-card" href="https://translate.google.com/" target="_blank" rel="noopener"><b>G Google Translate</b><p class="tool-note">Translation, camera and conversation tools.</p></a><a class="result-card" href="https://www.bing.com/translator" target="_blank" rel="noopener"><b>Microsoft Translator</b><p class="tool-note">Useful web-based backup.</p></a></div>`)}
async function weather(city,lat,lng){const el=modal(`${city} Weather ☀️`,`<div class="result-list" id="weatherResults"><div class="result-card">Loading the latest seven-day forecast…</div></div>`),results=el.querySelector('#weatherResults');try{const coords=lat&&lng?`&lat=${encodeURIComponent(lat)}&lng=${encodeURIComponent(lng)}`:'';const response=await fetch(`/api/weather?city=${encodeURIComponent(city)}${coords}`);if(!response.ok)throw new Error();const data=await response.json(),days=data.forecast||data.days||[];results.innerHTML=days.map(day=>`<article class="result-card"><b>${e(day.day||day.date)}</b><p class="tool-note">${e(day.summary||day.condition||'')} ${day.high!=null?`· High ${e(day.high)}°`:''} ${day.low!=null?`· Low ${e(day.low)}°`:''}${day.rainChance!=null?` · Rain ${e(day.rainChance)}%`:''}</p></article>`).join('')||'<div class="result-card">Forecast data is temporarily unavailable.</div>'}catch{results.innerHTML='<div class="result-card">The live forecast could not be reached.</div>'}}

async function refresh(){const button=document.getElementById('refreshDashboard');if(button){button.classList.add('loading');button.disabled=true;button.lastChild.textContent=' Updating…'}try{const registration=await navigator.serviceWorker?.getRegistration('/');if(navigator.onLine&&registration)await registration.update()}catch{}window.location.reload()}
function wireCommon(){document.getElementById('refreshDashboard')?.addEventListener('click',refresh);const archive=document.getElementById('archives');archive?.addEventListener('toggle',()=>{if(archive.open&&!archive.dataset.loaded){archive.querySelector('[data-archive-list]').innerHTML=archiveCards();archive.dataset.loaded='true'}});document.querySelectorAll('a[href="#archives"]').forEach(link=>link.addEventListener('click',()=>{archive.open=true}));document.querySelectorAll('[data-tool]').forEach(button=>button.addEventListener('click',()=>{const tool=button.dataset.tool;if(tool==='hungry'||tool==='spas')nearby(tool);if(tool==='translate')translate()}));document.querySelectorAll('[data-weather]').forEach(button=>button.addEventListener('click',()=>weather(button.dataset.weather,button.dataset.weatherLat,button.dataset.weatherLng)))}
function enableAwardTool(){const dock=document.querySelector('.dock-inner');if(!dock)return;dock.insertAdjacentHTML('beforeend','<button class="award-tool" type="button"><span>✈️</span>Award Flights</button>');dock.querySelector('.award-tool').addEventListener('click',awardFlights)}
function awardFlights(){const el=modal('Award flights ✈️',`<p class="tool-note">Search cached award availability. Confirm availability with the airline before transferring points.</p><form id="awardSearchForm" class="award-form"><div class="award-field-row"><label>From<input class="field" name="origin" inputmode="latin" autocapitalize="characters" placeholder="MCO, TPA" required></label><label>To<input class="field" name="destination" inputmode="latin" autocapitalize="characters" placeholder="LHR, CDG" required></label></div><div class="award-field-row"><label>Earliest departure<input class="field" name="startDate" type="date"></label><label>Latest departure<input class="field" name="endDate" type="date"></label></div><div class="award-field-row"><label>Cabin<select class="field" name="cabins"><option value="business">Business</option><option value="first">First</option><option value="premium">Premium economy</option><option value="economy">Economy</option><option value="">Any cabin</option></select></label><label>Sort by<select class="field" name="orderBy"><option value="lowest_mileage">Lowest points</option><option value="departure_date">Departure date</option></select></label></div><label class="award-toggle"><input name="direct" type="checkbox"> Nonstop flights only</label><button class="button primary" type="submit">Search award flights</button></form><div class="result-list award-results" id="awardResults"></div>`),form=el.querySelector('#awardSearchForm'),results=el.querySelector('#awardResults');form.addEventListener('submit',async event=>{event.preventDefault();const fields=new FormData(form),params=new URLSearchParams({origin:String(fields.get('origin')||'').toUpperCase().replace(/\s+/g,''),destination:String(fields.get('destination')||'').toUpperCase().replace(/\s+/g,''),take:'50',orderBy:String(fields.get('orderBy')||'lowest_mileage')});for(const key of ['startDate','endDate','cabins']){const value=String(fields.get(key)||'');if(value)params.set(key,value)}if(fields.get('direct'))params.set('direct','true');results.innerHTML='<div class="result-card">Searching award availability…</div>';try{const response=await fetch(`/api/award-search?${params}`),payload=await response.json();if(!response.ok)throw new Error(payload.error||'award_search_failed');const items=payload.results?.data||[];results.innerHTML=items.length?items.map(awardCard).join(''):'<div class="result-card"><b>No cached availability matched this search.</b><p>Try nearby airports, a wider date range, or another cabin.</p></div>'}catch(error){results.innerHTML=`<div class="result-card"><b>Search unavailable</b><p>${e(error.message==='award_service_rate_limited'?'The daily Seats.aero search limit has been reached. Try again after it resets.':'Award availability could not be reached. Check the airports and try again.')}</p></div>`}})}
function awardCard(item){const cabins=[['Y','Economy'],['W','Premium economy'],['J','Business'],['F','First']].filter(([code])=>item[`${code}Available`]).map(([code,label])=>{const points=item[`${code}MileageCost`],taxes=item[`${code}TotalTaxes`],seats=Number(item[`${code}RemainingSeats`]),cost=points?`${Number(points).toLocaleString()} pts`:'';return`<span class="award-cabin"><b>${label}</b>${cost?`<small>${e(cost)}${Number(taxes)>0?` + $${(Number(taxes)/100).toFixed(2)}`:''}</small>`:''}${seats>0?`<small>${seats} seat${seats===1?'':'s'} shown</small>`:''}</span>`}).join(''),route=item.Route||{},airlines=item.YAirlines||item.JAirlines||item.WAirlines||item.FAirlines||'';return`<article class="result-card award-card"><div class="award-card-head"><span>${e(item.Date||'Date unavailable')}</span><b>${e(route.OriginAirport||'')} → ${e(route.DestinationAirport||'')}</b><small>${e(item.Source||route.Source||'Award program')}${airlines?` · ${e(airlines)}`:''}</small></div>${cabins?`<div class="award-cabins">${cabins}</div>`:'<p>No cabin price is listed for this result.</p>'}</article>`}
async function offline(){const row=document.getElementById('offlineStatus');if(!row)return;if(!('serviceWorker'in navigator)){row.lastElementChild.textContent='Offline mode is unavailable in this browser';return}const paint=ready=>{row.classList.toggle('ready',ready&&navigator.onLine);row.classList.toggle('offline',!navigator.onLine);row.lastElementChild.textContent=!navigator.onLine?(ready?'Offline mode · saved trip ready':'Offline · open once online to save'):ready?'Offline ready · dashboard saved on this phone':'Saving dashboard for offline use…'};try{await navigator.serviceWorker.register(`/sw.js?v=${BUILD}`,{scope:'/'});await navigator.serviceWorker.ready;paint(true)}catch{paint(false)}window.addEventListener('online',()=>paint(true));window.addEventListener('offline',()=>paint(true))}

if(active)renderActive(active);else renderEmpty();
enableAwardTool();
offline();
})();
